### ISSUE TITLE
JEG and YARN Clustermode deployment question/issues

### ISSUE THREAD

**Issue by McKalvan** [jupyter/enterprise_gateway#787] opened 2020-03-03 17:06 UTC
Hello all.

I am currently attempting to deploy a dockerized EGW instance which will submit Spark Scala jobs in clustermode to an external YARN resource manager, but I am having some trouble with getting everything up and running. Does EGW have to be deployed on the YARN resource manager that I will be targeting or is setting the EG_YARN_ENDPOINT environment variable sufficient to connect? So far, I have been able to submit a Spark job and have it recognized by the YARN RM, however it appears to be stuck in an ACCEPTED state. Is this likely to be related to where I have deployed the EGW or is this more likely a configuration issue? 

sample of EGW log:
``jupyter-enterprise-gateway_1  | [D 2020-03-03 16:53:55.513 EnterpriseGatewayApp] 57: State: 'ACCEPTED', Host: '<HOST>', KernelID: '6ec2d7f0-c819-48e0-9b79-33c47c3b9b17', ApplicationID: 'application_1581379345744_71444'
  2 jupyter-enterprise-gateway_1  | [D 2020-03-03 16:54:00.518 EnterpriseGatewayApp] Waiting for KernelID '6ec2d7f0-c819-48e0-9b79-33c47c3b9b17' to send connection info from host '<HOST>' - retrying...
  3 jupyter-enterprise-gateway_1  | [D 200303 16:54:01 connectionpool:437] http://<YARN RM>:8088 "GET /ws/v1/cluster/apps/application_1581379345744_71444 HTTP/1.1" 307 133
  4 jupyter-enterprise-gateway_1  | [D 200303 16:54:01 connectionpool:437] http://<YARN RM>:8088 "GET /ws/v1/cluster/apps/application_1581379345744_71444 HTTP/1.1" 200 None
  5 jupyter-enterprise-gateway_1  | [D 200303 16:54:01 base:100] 'GET' request against endpoint 'http://<YARN RM>:8088/ws/v1/cluster/apps/application_1581379345744_71444' took 12.704 ms
  6 jupyter-enterprise-gateway_1  | [D 2020-03-03 16:54:01.032 EnterpriseGatewayApp] 58: State: 'ACCEPTED', Host: '<HOST>', KernelID: '6ec2d7f0-c819-48e0-9b79-33c47c3b9b17', ApplicationID: 'application_1581379345744_71444'
  7 jupyter-enterprise-gateway_1  | [D 2020-03-03 16:54:06.038 EnterpriseGatewayApp] Waiting for KernelID '6ec2d7f0-c819-48e0-9b79-33c47c3b9b17' to send connection info from host '<HOST>' - retrying...
  8 jupyter-enterprise-gateway_1  | [D 200303 16:54:06 connectionpool:437] http://<YARN RM>:8088 "GET /ws/v1/cluster/apps/application_1581379345744_71444 HTTP/1.1" 307 133
  9 jupyter-enterprise-gateway_1  | [D 200303 16:54:06 connectionpool:437] http://<YARN RM>:8088 "GET /ws/v1/cluster/apps/application_1581379345744_71444 HTTP/1.1" 200 None
 10 jupyter-enterprise-gateway_1  | [D 200303 16:54:06 base:100] 'GET' request against endpoint 'http://<YARN RM>:8088/ws/v1/cluster/apps/application_1581379345744_71444' took 12.426 ms
 11 jupyter-enterprise-gateway_1  | [E 2020-03-03 16:54:06.551 EnterpriseGatewayApp] KernelID: '6ec2d7f0-c819-48e0-9b79-33c47c3b9b17', ApplicationID: 'application_1581379345744_71444' unexpectedly found in state 'FAILED' during kernel startup!
 12 jupyter-enterprise-gateway_1  | [E 200303 16:54:06 web:2246] 500 POST /api/kernels (172.28.0.1) 217355.68ms
 13 jupyter-server_1              | [W 16:54:06.555 LabApp] 500 POST /api/sessions?1583254229200 (10.140.210.136): Error attempting to connect to Gateway server url 'http://<GATEWAY>:8888'.  Ensure gateway url is valid and the Gateway instance is running.
 14 jupyter-server_1              | [W 16:54:06.556 LabApp] Error attempting to connect to Gateway server url 'http://<GATEWAY>:8888'.  Ensure gateway url is valid and the Gateway instance is running.``

stdout in YARN application log:
`org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:468)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:779)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:778)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:803)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)`

**Comment by lresende** [comment] 2020-03-03 17:11
The Gateway will try to launch the kernel, which will then submit back details of where the kernel is running. In a containerized environment, do you have proper network connectivity/visibility between the two nodes?

**Comment by McKalvan** [comment] 2020-03-03 17:32
Thanks for the lightning fast reply!

Currently, the connection between the Jupyter Server and the gateway that I am hosting all of the kernels on seems to be working fine. I am not sure exactly if/how to check the connectivity between the the docker container that I am running EGW in and the target YARN cluster though. The YARN RM does accept the spark submission that is kicked off by the startup script of my YARN kernel, so there is some sort of connection there. From there, it just stays stuck in ACCEPTED state for some reason. Given the size of the YARN cluster that I am targeting, I don't believe this is related to any sort of resource constraints. Just to be safe, I turned down the requested resources and ran into the same issue as before.

**Comment by kevin-bates** [comment] 2020-03-03 17:50
Could you please attach the complete set of log entries that includes the kernel's initial start sequence, along with the complete stdout YARN log entries (preferably with newlines preserved)?

Spark-based YARN applications will stay in the ACCEPTED state until the spark context is created - at which time they should move to RUNNING.  Once EG has obtained the application_Id and host information (via the kennel launcher response back to EG), then it considers the kernel started and allows for things like kernel-info request/reply, etc.  I'd like to see that interaction in a more readable (and complete) log.

One issue with interacting with an external resource manager from a container is that the container's network would need to be set up as a host network so that the response can be returned from YARN.  I'm assuming you have that portion set up correctly but I thought it worth a mention.

**Comment by McKalvan** [comment] 2020-03-03 19:21
Here is the YARN stdout: 
[yarn-stdout.txt](https://github.com/jupyter/enterprise_gateway/files/4283104/yarn-stdout.txt)
The logs from the JEG instance upon starting up the YARN based kernel:
[JEG-logs.txt](https://github.com/jupyter/enterprise_gateway/files/4283111/JEG-logs.txt)

I have omitted some details for security, but otherwise the startup/failure of the kernel should be there. Please let me know if you are in need of any additional information!

**Comment by kevin-bates** [comment] 2020-03-04 18:43
@McKalvan - thank you for the logs - sorry for the delayed response.

Although the YARN logs don't apply to the same application as what's in the EG logs, I'm assuming the problem is the same.  The YARN logs appear to be about 45 minutes earlier than the EG logs and reference application ID `application_1581379345744_71574` vs `application_1581379345744_71705` in the EG logs.

As best as I can tell, it looks like the launched kernel is unable to communicate its connection information back to EG.  As a result, EG continues polling until the kernel launch timeout is reached.

The YARN node is supposed to send the connection information to `172.28.0.3:51876` which should correspond to the IP of the EG server - on which it should be listening on `51876`.  However, it produces this log entry:
```
2020-03-03 18:01:39,256 ERROR [Driver] yarn.ApplicationMaster (Logging.scala:logError(91)) - User class threw exception: java.net.ConnectException: Connection timed out (Connection timed out)
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at launcher.utils.SocketUtils$.writeToSocket(SocketUtils.scala:26)
	at launcher.ToreeLauncher$.initProfile(ToreeLauncher.scala:222)
	at launcher.ToreeLauncher$.main(ToreeLauncher.scala:297)
	at launcher.ToreeLauncher.main(ToreeLauncher.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
```
This exception is not handled by the launcher (I suppose we could retry a couple of times, then gracefully exit) so the application gets shut down.

Meanwhile, EG is stuck `Waiting for KernelID '448d3bd8-edb4-4114-8b15-e4ab82442a94' to send connection info from host '<TASK HOST>' - retrying...` until it times out.

I see that you're using Kerberos - at least I glean that from this replaced entry on like 27 of the EG log: `<KERBEROS AUTH>`.  If this is the case, its doesn't appear as though you've set the env `EG_IMPERSONATION_ENABLED=True`, otherwise we'd see the message:
```
Starting Scala kernel for Spark in Yarn Cluster mode as user yarn
```
but instead, we see:
```
Starting Scala kernel for Spark in Yarn Cluster mode on behalf of user yarn
```

Here's that portion of the run.sh script provided in the repo.  You can see that when impersonation is enabled, the `--proxy-user` is provided.
```bash
if [ "${EG_IMPERSONATION_ENABLED}" = "True" ]; then
        IMPERSONATION_OPTS="--proxy-user ${KERNEL_USERNAME:-UNSPECIFIED}"
        USER_CLAUSE="as user ${KERNEL_USERNAME:-UNSPECIFIED}"
else
        IMPERSONATION_OPTS=""
        USER_CLAUSE="on behalf of user ${KERNEL_USERNAME:-UNSPECIFIED}"
fi
```

The other odd thing is that the user `yarn` is appearing in your message, while this log message: 
```
jupyter-enterprise-gateway_1  | [D 2020-03-03 18:45:32.705 EnterpriseGatewayApp] BaseProcessProxy.launch_process() env: {'PATH': '/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'KERNEL_LAUNCH_TIMEOUT': '40', 'KERNEL_USERNAME': 'svc_hadoop_dpluser', 'KERNEL_WORKING_DIR': '/home/<USER>/work/ckessler', 'SPARK_HOME': '/home/vccorp/hadoop-role-skeleton/apps/spark-2.4.3-bin-hadoop2.7', '__TOREE_SPARK_OPTS__': '--master yarn --deploy-mode cluster --queue root.heds.data.prod --name ${KERNEL_ID:-ERROR__NO__KERNEL_ID} --conf spark.yarn.submit.waitAppCompletion=false --conf spark.yarn.am.waitTime=1d --num-executors 10 --executor-memory 16g --driver-memory 4g', '__TOREE_OPTS__': '--alternate-sigint USR2', 'LAUNCH_OPTS': '', 'DEFAULT_INTERPRETER': 'Scala', 'KERNEL_USER': '<USER>', 'KERNEL_GATEWAY': '1', 'EG_MIN_PORT_RANGE_SIZE': '1000', 'EG_MAX_PORT_RANGE_RETRIES': '5', 'KERNEL_ID': '448d3bd8-edb4-4114-8b15-e4ab82442a94', 'KERNEL_LANGUAGE': 'scala', 'EG_IMPERSONATION_ENABLED': 'False'}
```
is showing `KERNEL_USERNAME` as `svc_hadoop_dpluser`.  Have you modified the run.sh script to set the user as 'yarn'?

When Kerberos (and impersonation) is properly configured, we should see:
```
Starting Scala kernel for Spark in Yarn Cluster mode as user svc_hadoop_dpluser
```
and the applications in the YARN dashboard should appear as though user svc_hadoop_dpluser is running them.

If you still have issues, it might be helpful to provide correlated logs so we can get a more precise idea of the timing.  You might also check this section of the docs if Kerberos is your intention: https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-security.html#user-impersonation

**Comment by McKalvan** [comment] 2020-03-04 19:18
Regarding the yarn/svc_hadoop_dpluser user detail, I believe my changes to the run.sh startup script crossed some wires w/ my environment variables and things got mixed up. I have made some changes so that now everything is running as svc_hadoop_dpluser.

I have set EG_IMPERSONATION_ENABLED to true and the exception in the JEG logs is now showing:

`java.net.ConnectException: Call From 95aeba99adbc/192.168.128.2 to <YARN RM Host>.net:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused`

Which seems to reinforce what you said about this being a connection issue between EG and the kernel hosted on the YARN RM. In this case however, it doesn't seem like there is any connection made at all between EG and YARN (IE no application gets accepted by YARN). 

> The YARN node is supposed to send the connection information to 172.28.0.3:51876 which should correspond to the IP of the EG server - on which it should be listening on 51876.

Is this something that I need to configure w/in my docker container? Would I need to at the very least expose 51876 in my container?

**Comment by kevin-bates** [comment] 2020-03-04 19:44
Oh - right, EG is running in a container - that slipped my mind.  I knew the `172.x.x.x` address seemed familiar!  So that's why YARN can't respond, it doesn't see that IP.

This port is dynamic and per kernel, so its exposure is not really an option.  Are you able to configure host-network for your container?

**Comment by McKalvan** [comment] 2020-03-04 19:51
I believe so

**Comment by McKalvan** [comment] 2020-03-05 22:02
Sorry, I am now realizing that my last comment was a bit vague. I believe that I do have the ability to configure the host-network for my container, however I am not sure what I should be changing. If this is not an issue that can be solved via exposure,  what should I be doing on my end to ensure that the kernel in YARN is able to relay information back to the JEG instance in my container?

As a side note, thank you for your assistance thus far. I've been beating my head into the wall for a bit now and I am finally feeling like I have some direction w/ this endeavor.

**Comment by kevin-bates** [comment] 2020-03-06 16:57
(Disclaimer: not an expert on [docker networking](https://docs.docker.com/network/))
By telling the container you're using the host's network, then the IP and (dynamic) port are accessible from outside the container as if EG is running on the host.  This would change the response address from a `172.x.x.x` value to something the kernel launcher can respond to with its connection information.  Hmm, this option may only be available in Docker swarm.

Is there a reason you need to run EG in a container and not on an edge or master node directly?

**Comment by McKalvan** [comment] 2020-03-06 18:21
I believe you are correct on the Docker swarm part; I've got JEG set up in the host network and I am still seeing the local ip address being used in the container. I'll give it a shot w/ Docker swarm to see if that clears anything up.

I have a slight preference to set this up in a container for purely non-technical reasons as setting it up on the edge/master node would require some paperwork/meetings in my organization, which I would prefer to avoid if possible.

**Comment by McKalvan** [comment] 2020-03-10 21:54
Huzzah! I was able to get a a running kernel with a Spark context using network_mode: host w/ docker compose. Docker swarm does seem to be a little more tricky as I can't find any straight forward way of exposing an arbitrary number of ports using host networking in a compose file, but I blame this on my inexperience w/ Docker more than anything else.

**Comment by kevin-bates** [comment] 2020-03-10 22:05
Fantasic news @McKalvan!  If you don't mind writing up what you did to get the networking correct, I think we could probably create a section on [this page](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-docker.html#enterprise-gateway-deployment) somewhere that describes the containerized deployment of EG in on-prem environments - or something to that affect.  I'm sure others would benefit from your experiences.

**Comment by McKalvan** [comment] 2020-03-12 18:47
@kevin-bates  Of course! I've got some cleanup work that I've got to do to get this deployed, but once that is done, I'll do a quick write up to summarize the solution to this issue.

**Comment by McKalvan** [comment] 2020-03-24 18:46
Also figured out the dockers swarm deployment issue I was having before. It has nothing to do w/ JEG but as a general note, when deploying to docker swarm using a docker compose file (I believe the compose version needs to be 3.2 or higher), one needs to reference the host network as an external network in the "networks" property in the compose file: IE:

`networks:
        host:
                external: true`

From here, just add "host" to the networks in each service as one would for any other service and deploy.

**Comment by kevin-bates** [comment] 2020-03-24 20:48
Great news @McKalvan - this is greatly appreciated!

**Comment by kevin-bates** [comment] 2020-03-31 16:39
Hi @McKalvan - could you please share your changes to the [docker-compose.yml](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/docker-compose.yml) file in order to have an containerized EG (running in Swarm) talking to an Hadoop YARN cluster?

I'm assuming the changes are in these areas: [`services.networks`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/docker-compose.yml#L29-L30) and/or [`networks`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/docker-compose.yml#L46-L47).

We'd like to produce a release soon and it would be great if we could include these updates then.  Thank you.

**Comment by McKalvan** [comment] 2020-03-31 18:45
@kevin-bates Apologies for the delay! 

Here's a quick summary of the changes:

I added the following my docker compose file:

networks:
    host:
        external: true

and then I added the following to each service: 

networks:
     - host

Because I was also working w/ multiple YARN clusters, I also found it easier to setup the YARN RM endpoint by just adding them to the config section of each kernel.json file, EX:

      "config": {
      	"yarn_endpoint": "<YARN RM>",
      	"alt_yarn_endpoint": "<YARN RM HA>",
        "port_range": "<PORT RANGE>"
      }

**Comment by kevin-bates** [comment] 2020-03-31 19:22
Thank you for the quick response.

Did these network entries _replace_ those named `enterprise-gateway`, or are they _in addition to_ the existing entries?

Nice use of the kernel.json file's metadata.process_proxy.config section!  That's exactly the intent.

Just curious, are you using port-ranges as well?  (Never sure how often those kinds of things are used.)

**Comment by McKalvan** [comment] 2020-03-31 20:52
I replaced all other network entries w/ just a single "host" network entry. My understanding of docker host networking is that any service that uses host networking can only have the host network as the sole network of the service. 

I'm using port-ranges to limit JEG to very isolated port ranges purely out of extreme precaution to avoid port conflicts between other processes that also require ports on the box that I am running my jupyter stack off of. This may be a bit unnecessary, but since my stack is running on the host network, it does run some (very) small chance of clashing w/ other processes.

**Comment by kevin-bates** [comment] 2020-03-31 21:30
I'm sorry to keep going back and forth, but this is the kind of thing I'm unable to test.  Here's minimally what I'd like to see.  I'd like to include a [`docker-compose.yml`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/docker-compose.yml) file with comments similar to the following in the following sections.  Could you please either provide the file you used, or modify the contents in a generic manner such that the proper networking can be set up?

```
services:
...
    networks:
      # Note: If Enterprise Gateway will be managing kernels external to the Docker cluster, replace
      # the '"enterprise-gateway"' network entry with the following by removing the comment.
      #- host
      - "enterprise-gateway"
    ports:
      - target: ${KG_PORT:-8888}
        published: ${KG_PORT:-8888}
        protocol: tcp
        mode: host
    labels:
      app: "enterprise-gateway"
      component: "enterprise-gateway"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      labels:
        app: "enterprise-gateway"
        component: "enterprise-gateway"

networks:
  # Note: If Enterprise Gateway will be managing kernels external to the Docker cluster, replace
  # the 'enterprise-gateway:' network entry with the following two lines by removing the comment.
  #host:
  #  external: true
  enterprise-gateway:
```
I'm fairly certain the first `- host` reference is wrong.  Also, what happens to `ports:` in this case?
A pull request would be much appreciated?

**Comment by kevin-bates** [comment] 2020-06-03 00:03
Closing. See comments: https://github.com/jupyter/enterprise_gateway/issues/787#issuecomment-606804930 and https://github.com/jupyter/enterprise_gateway/issues/787#issuecomment-606868792 for assistance.

**Closed by kevin-bates** 2020-06-03 00:03 UTC
Labels: Configuration, Docker, Question, YARN
