### ISSUE TITLE
Support for tornado version 6

### ISSUE THREAD

**Issue by Gsbreddy** [jupyter/enterprise_gateway#598] opened 2019-03-12 11:14 UTC
Hi All, I observed the latest tornado i.e, 6.0.1 is not compatible with EG. But the latest jupyter-lab is running on tornado 6.0.1. So if I am trying to use EG with latest jLab it's failing. 
The issue I think is probably in establishing the websocket connection between EG and notebook server. Can anyone please check this. Thanks.

**Comment by kevin-bates** [comment] 2019-03-12 14:09
Hello - this sounds like a duplicate of #597 - which requires an update to NB2KG.  Could you please confirm that the error message information is similar to #597?  Once confirmed, I'll close this as a duplicate.

This is all related to the recent tornado 6.0 version.  There are new versions of Notebook (5.7.5+) to address this issue, but I see there's a need to update NB2KG.

FYI: Once the 6.0 release of Notebook comes out, NB2KG will be embedded, so that won't be a worry any longer.

**Comment by kevin-bates** [comment] 2019-03-12 14:29
Hmm - looks like you might need to enable debug logging on your notebook/lab instance...
```
[D 07:27:42.239 NotebookApp] Initializing websocket connection /api/kernels/e192ca76-dc43-4779-9afa-8a32bc23a1a0/channels
/opt/anaconda3/envs/nb2kg-dev/lib/python3.7/site-packages/nb2kg/handlers.py:87: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super(WebSocketChannelsHandler, self).get(kernel_id=kernel_id, *args, **kwargs)
```

**Comment by kevin-bates** [comment] 2019-03-12 16:07
Note that [NB2KG 0.6.0](https://pypi.org/project/nb2kg/) has been released to address this issue.  Please update NB2KG and try again.

**Comment by kevin-bates** [comment] 2019-03-13 15:57
I'm fairly certain this is related to a faulty NB2KG following Tornado installs of 6.0.1 - so I'm going to close this for now.  Feel free to re-open should the problem persist.

**Closed by kevin-bates** 2019-03-13 15:57 UTC
Labels: Configuration, Dependency
