### ISSUE TITLE
Error on running spark python notebook

### ISSUE THREAD

**Issue by suryag10** [jupyter/enterprise_gateway#691] opened 2019-06-18 19:12 UTC
Hi,
I am using EG 2.0.0rc1 release and tried to spawn notebooks spark python on k8s and python on k8s as well and tried to execute following code snippet:

import numpy as np
def funct(L):
  return np.exp(-gamma*L)
gamma=1
funct(2)

The above executes perfectly incase of Python, but doesnt work in spark python notebook and gives the following error:

NameErrorTraceback (most recent call last)
/usr/local/bin/kernel-launchers/python/scripts/launch_ipykernel.py in <module>()
      4   return np.exp(-gamma*L)
      5 gamma=1
----> 6 funct(2)

/usr/local/bin/kernel-launchers/python/scripts/launch_ipykernel.py in funct(L)
      2 
      3 def funct(L):
----> 4   return np.exp(-gamma*L)
      5 gamma=1
      6 funct(2)

NameError: global name 'np' is not defined.

Need Help in this regard.
Spark Version used is 2.4.0

**Comment by suryag10** [comment] 2019-06-18 19:17
![python_noError](https://user-images.githubusercontent.com/42367117/59712897-ca7dc580-922b-11e9-9002-f8e2915a2324.PNG)
![Spark_Error](https://user-images.githubusercontent.com/42367117/59712905-cfdb1000-922b-11e9-93fc-9ceb87dfc67b.PNG)

**Comment by kevin-bates** [comment] 2019-06-18 20:10
I'm fairly certain this is related to #687.  I have pushed two images [`elyra/kernel-py:scope`](https://hub.docker.com/r/elyra/kernel-spark-py/tags) and [`elyra/kernel-spark-py:scope`](https://hub.docker.com/r/elyra/kernel-py/tags) that have been build with the current PR #688 - although the fix is not final.

**Comment by suryag10** [comment] 2019-06-18 20:18
Thx kevin for the update. Will try to use https://github.com/jupyter/enterprise_gateway/pull/688/files and update.

**Comment by suryag10** [comment] 2019-06-19 04:04
Hi Kevin,
I had tested the same and is working as expected. Thx for the timely help.

**Comment by kevin-bates** [comment] 2019-06-19 14:55
Great news - thank you for trying it out so quickly.  Although that may not be the final change, we know this is the same issue, so I'm closing this as a duplicate of #687.

**Closed by kevin-bates** 2019-06-19 14:55 UTC
Labels: Duplicate, Python kernel (iPython), Spark
