### ISSUE TITLE
Add support for varying numbers of user-specified mounts/PVs.

### ISSUE THREAD

**Issue by rayh** [jupyter/enterprise_gateway#527] opened 2018-12-11 05:50 UTC
Doing so would allow the kernel to work as if it was local to the notebook - i.e. load other files from the FS.  And modifications made to the FS in the kernel are reflected in the notebook.

I'm using AWS EFS (i.e. NFS) for user's home directories and so it can be mounted many times.  My k8s foo is not strong enough to know how this might work - but I imagine introspecting the notebook's pod and copying the required volumes to the kernel's node might work?

Of course, this wouldn't work for EBS backed PVs

**Comment by kevin-bates** [comment] 2018-12-11 16:39
Hi Ray.  This is an area we've essentially left as an integration point due to the variance in solutions - as you point out as well.  For YARN configurations, we recommend HDFS or COS, etc.  Its one of those areas that becomes a bit of a slippery slope for general solution providers like EG.

For K8s, we first recommend that the kernelspecs used by the EG pod be placed into NFS.  The `enterprise-gateway.yaml` file provides mounting statements (commented out) to lend some insight to this already..  The idea is that users can then customize the `kernel-pod.yaml` file (or any other aspect of the kernelspec hierarchy), potentially for each different kernelspec, as they see fit. 

One thing to note is that **all** `KERNEL_`-prefixed env variables present in the `env` entry of the json body in the kernel creation request will be available to the `kernel-pod.yaml` file.  This, coupled with the knowledge that the `NB2KG` notebook extension does the same thing (it adds any `KERNEL_`-prefixed env variables to the json body of the kernel creation request), allows these specially-named variables to _flow_ from the notebook server to the kernel-pod and, by adding into the env for the launched pod, the kernel container itself.   As a result, the final "glue" for Jupyter Hub integrations would be to map the hub-based values (Hub user, Hub user home) to `KERNEL_` variables when launching the notebook pod.

Please note that we already define `KERNEL_USERNAME`. This, if it isn't already, needs to map to the hub user value.  If a user's home can be inferred from their name, then this would be sufficient.  Else you'd want to create another variable like `KERNEL_USER_HOME` that conveys the directory.

**Comment by rayh** [comment] 2018-12-12 01:15
This is a bit of an issue as it breaks the user's mental model of how notebooks work.  They cannot load files from the filesystem (configs, data files, etc) that they can see in Jupyter.  

Thinking out loud, my initial thinking went something like:

1. JupyterHub creates a notebook
2. Jupyter notebook asks EG for a kernel
3. EG introspects callers pod and copies volumes/mounts to the kernel pod definition
4. EG k8s launcher  creates kernel pod

But, to use the something like KERNEL_, it could work like:

1. JupyterHub creates a notebook (and passes down the volume config as an ENV variable)
2. Jupyter notebook asks EG for a kernel (and passes on the above ENV variable)
3. EG replaces args in kernelspec with ENV variable contents
4. EG k8s launcher creates kernel pod (with volume mounts)


An alternative would be to ship the files over to the kernel as they are loaded... but i think that would be quite tricky to intercept reliably.

**Comment by kevin-bates** [comment] 2018-12-12 01:39
Exactly.  Your second set of bullets is essentially how it works.  Touch points for possibly gathering and/or converting variables are in the Jupyter Hub config to control the notebook configuration, and in the `kernel-pod.yaml` file, located in the `scripts` sub-director of the directory containing `kernel.json`.

**Comment by rayh** [comment] 2018-12-21 05:15
Ok, I've tried to make this work by altering `launch_kubernetes.py` to inject the volume/volumeMounts based on an env variable.  However, when the pod is started, it doesnt have these volumes.  Is something trying to update/rewrite the volume definition of these kernel pods?

**Comment by kevin-bates** [comment] 2018-12-21 16:18
Hi Ray - a couple questions, comments.

`launch_kubernetes.py` is located in a single location in the repo, but distributed to each k8s kernelspec at runtime.  Just want to make sure that the kernelspec `scripts` directory referenced in the EG pod has your modified `launch_kubernetes.py`.

What variables are used to manipulate your PV/PVC activities?  Are those values getting to the `launch_kubernetes.py` script?  (I believe we dump the env into the EG log when a kernel is launched, so that might help.)

Seems like a lot of this kind of work would take place in the adjacent `kernel-pod.yaml` file using curly-braced variables to map to the envs.  Did you do that as well?

Perhaps you can share your `launch_kubernetes.py` and `kernel-pod.yaml` changes and I can lend another pair of eyes?  Since the launcher already handles PV/PVC stanzas, I wouldn't expect there to be any changes required.

**Comment by kevin-bates** [comment] 2019-01-05 18:37
@rayh, any update on this?

**Comment by rayh** [comment] 2019-01-06 23:41
I did start by adjusting the kernel-pod.yaml, but i think it would need to use a more full featured template engine as i wanted to perform loops over an array of volumes.  The reason being is that our users will have a personal home directory as well as one or more team/project drives.

In my setup, I moved the common scripts to a separate directory, so there is only one copy of `launch_kubernetes.py`.  I can see in the logs that the k8s client is creating the pod with my modified spec.  In order to isolate this issue, I just hardcoded the mounts within the script, so there are no ENV variable dependencies for now.

My modified script is here: https://gist.github.com/rayh/4042873d761a1eb30e98610d3647f3c5

The kernel-pod.yaml is unmodified.

**Comment by kevin-bates** [comment] 2019-01-07 00:56
Thanks for the update.  Yeah, a variable number of mounts between requests will be problematic.  I would prefer we not modify `launch_kubernetes.py` at all, and, had the number of mounts been static between your users, this could have been easily achieved via `kernel-pod.yaml` - which was the intent.

I still like the idea of exposing `kernel-pod.yaml` to allow for customizations, but even that doesn't provide a way for this _dynamic PV_ behavior.  This is only an issue with _bring your own namespace_ usage since the PVs and PVCs have already been created and you just need to _connect_ the pod to the PV.  That said, we could add support for something like `KERNEL_NAMESPACE_VOLUMES`iinto `launch_kubernetes.py` using an encoding like you provided.  If we take that approach, we might want to ensure the pod that is getting extended is indeed a kernel pod (via the component label) in case a custom kernel-pod.yaml happens to define multiple pods.  (Also, the reason for using `KERNEL_NAMESPACE_VOLUMES` is to emphasize this is used only in _BYONampespace_ situations.)

Ideas ...
Are the PV and PVC names the same as what they were created with? 
I would try with just one PV/PVC combo and see if a single entry in your mounts list works?
Lastly, perhaps there's something special with `/home/jovyan` in that that's the users's home directory.  In fact, I would recommend a different mount point since images are likely setup with various artifacts present in the default home directory and mounts over that directory will void those files.

**Comment by rayh** [comment] 2019-01-07 01:11
Yeah, there is a danger that `/home/jovyan` might contain something special in the kernel - but I'm unsure how else to make kernels work as a user would expect; i.e. that the filesystem they can see in the jupterlab browser is available in the notebook. How would you approach this?  imagine that there is a git project checked out that contained a notebook and some CSV files - how would you load the CSV  into the notebook?

**Comment by kevin-bates** [comment] 2019-01-07 01:44
I think the kernel is fine relative to the home folder. I was more concerned about the base Jupyter stuff. If there's a dependency on existing files in the image home directory, then perhaps it should be the responsibility of the integration to preserve those files in mounts. That seems reasonable to me.

I agree that we need to mounts to /home/jovyan.

Can you describe what happens if mounting a single directory? Probably best to leave the home directory or of this question.
How are these mounts exposed to k8s? Have you confirmed those same mounts work with non-kernel pods and that those equivalent steps have been performed by the EG code (minus creation of the pv and pvc)?

**Comment by kevin-bates** [comment] 2019-01-07 02:39
Hmm. Are you attempting to use the same pvc for both pods at the same time? There are restrictions between PVs and PVCs. I can't look right now but I remember there being some obnoxious restrictions in that area.

What do the k8s logs and describe outputs show for the kernel pod?

**Comment by kevin-bates** [comment] 2019-01-11 16:40
@rayh - it has occurred to me that if you're using the spark-based kernel images, then this would explain why you're not seeing any of your changes take affect.  This is because the launch_kubernetes and kernel-pod.yaml files do not apply to k8s spark invocations since the kernel-image's pod creation is completely triggered via `spark-submit`.

Mounts for the spark-based images must be provided via the SPARK_OPTS entries using the specific config options: https://spark.apache.org/docs/latest/running-on-kubernetes.html#using-kubernetes-volumes

Regarding your environment... Varying the customizations (mounts, etc.) at a _per-user_ level is going to be problematic.  Having _fixed sets_ of custom resources across all users of a given kernelspec fits the current modeling better - although even for the Spark images, this is challenging.

One approach would be to have different kernelspecs for different numbers of mounts.

What we really need are _dynamic kernelspecs_, but we're not there yet.

How do you handle the varying number of mounts in your JupyterHub configuration.  Is this something done via Helm charts and helm allows the ability to add complete objects based on some condition?  I.e., how do the notebook/lab pods launched from Hub know to mount 2 directories for user A and 3 directories for user B?

**Comment by esevan** [comment] 2019-01-15 06:06
Hi, I've tried `enterprise-gateway` recently, and super interested in the project.
I've figured out the solution by simple workaround as @kevin-bates recommended.
> Customize kernel-pod.yaml

I set the JupyterHub configuration `singleuser.storage.dynamic.pvc-name-template` to claim-{username}, and modify kernel-pod.yaml to mount that PVC on same directory by importing username as kernel user name env.

OK, it works as long as PVC is created as RWX mode, but here's the problem.
My approach, which might be similar with the solution this issue thread is heading for, won't work if kernel pod is spawned in other namespace than the namespace the jupyter lab pod is spawned in.

PVC is a namespaced resource and PV is a non-namespaced resource. I think it's better to use PV than PVC to mount user volume. Otherwise, kernel namespace option should be disabled to use this feature.

BTW, here are the problems I faced. Hope that this feature is enabled and released soon!
- Notebook pod user UID should be same as kernel user UID.
- Service account RBAC
- PVC should be created with RWX mode.

**Comment by kevin-bates** [comment] 2019-01-15 15:12
@esevan - thanks for the comment.  Ray's primary issue is that he'd like to _vary_ the number of mounts on a per-request basis - since different users have different requirements.  This doesn't fit the current customization model of updating the `kernel-pod.yaml` - which works when the number of mounts are fixed.  In addition, users wishing to use the spark-based images have another issue in that we (EG) don't control the pod definition.  This is performed by the Spark code.  The only influence we have is based on the various Spark config options available.

Regarding your issues...
>My approach, which might be similar with the solution this issue thread is heading for, won't work if kernel pod is spawned in other namespace than the namespace the jupyter lab pod is spawned in.

EG supports _bring your namespace_ so the kernel-based pods (vanilla and Spark) can be launched within an existing namespace.  To enable this behavior, set the `KERNEL_NAMESPACE` env variable in your Notebook/Lab instance to the name of the appropriate namespace.  The NB2KG extension automatically forwards all `KERNEL_`-prefixed env variables in the json body of the kernel creation request.  EG will see this value and use that value for the pod's namespace.  As noted [here](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-kubernetes.html#namespaces), you must also pass `KERNEL_SERVICE_ACCOUNT_NAME` to provide the appropriate RBAC control for the kernel pod.

>Notebook pod user UID should be same as kernel user UID.

Although not explicitly supported, nor have I tried this, you should be able to update the kernel-pod.yaml with a securityContext stanza as follows:
```yaml
spec:
  securityContext:
    runAsUser: ${kernel_uid}
    fsGroup: ${kernel_gid}
```
and, on your Notebook/Lab instance, set envs: `KERNEL_UID` and `KERNEL_GID`.  The `KERNEL_` variables will flow and be available to the kernel pod's creation.  (All `KERNEL_XXX` values are available to the kernel-pod.yaml as `${kernel_xxx}` - lowercase.)

We should probably have EG know about `KERNEL_UID` so that users can't do `KERNEL_UID=0`.  (I'd probably add a `EG_UID_BLACKLIST` that defaults to 0, but always a list of values.  Same for GID.) .

I also don't yet know if there are changes required within the various kernel images to support this.  I would imagine a GID of `100` might be necessary at the moment.  It would be awesome if you want to try this.

I've gone ahead and created Issue #548 for this.  Thanks!

**Comment by kevin-bates** [comment] 2019-02-09 00:22
@rayh - not sure you watch the repo, but PR #571 might interest you.  When coupled with an updated NB2KG, EG will set the kernel image's working dir relative to where the current notebook file resides.  So, assuming the container has appropriate mounts such that that path equates to the user's notebook server, then files present in the local notebook directory will be available to the kernel.  We have some user's adopting this in their Hub k8s configurations already.  You'll likely need to add appropriate mount commands using ${kernel_...} substitutions to get the *per-user* variations.

What this still doesn't address is varying "mount counts" for different users.  Still thinking about that, but I tend agree some kind of KERNEL_EXTRA_POD_MOUNTS thing may be the way to go - with logic similar to what you provided, although I'd prefer it take actual json-ized strings that we then "inject" into the appropriate locations during the processing of the kernel-pod.yaml.

In addition, the kernel-working-dir functionality is not available to the spark-based kernels since they don't support the ability to change the working directory.  I'm hoping that lack of support will go away once they release their support for POD templates.

Since this Issue has morphed into really being about varying mount points and doesn't really match that of the title. I'm wondering if we shouldn't close this issue and open one that is specific to varying mounts on a per-kernel basis.  We could also rename it, but it seems much of its discussion is really about other things.

Please let me know your thoughts on this.  Thanks.

**Comment by kevin-bates** [comment] 2019-03-18 21:04
@rayh - I've gone ahead and changed the title of this issue since we can today (especially with #571) support the mounting of the hub user's home directory to the kernel pod.  Where things went sideways in your requirements was when user A needs 3 mounts and user B needs 2 mounts.  Unless the "mount count" is the same, we have trouble short of having, as you said above, a more dynamic means of addressing this.

**Comment by esevan** [comment] 2019-03-29 13:27
Can we use jinja2 template for `kernel-pod.yaml`?
Recently It is getting messed up by adding static vars to `kernel-pod.yaml` and optional or dynamic variables to `launch_kubernetes.py` in my personal customization.

If we use jinja2 template then `kernel-pod.yaml` could be more customizable IMHO.

**Comment by kevin-bates** [comment] 2019-03-29 14:49
This sounds like an interesting approach (note: I have zero experience with jinja2 other than the google I just performed :smile:), although I'd like to understand how this resolves varying number of items that get produced into the final result.  Specifically, what kinds of issues are you trying to resolve?

From a functional standpoint, this sounds like it would be similar to what has been submitted to support [kernel pod templates for Spark](https://github.com/jupyter/enterprise_gateway/pull/559) where the "final result" lies in a directory (e.g., `/tmp`) in a filename of `kpt_<kernel_id>`.  Since we'll want any solution to also support that future functionality, I suppose that implies two things:  
1. the "result yaml" should be persistent (and removed no later than following the kernel's shutdown)
2. the "result yaml" must be unique to the kernel being launched (which is solved due to the first point along with the kernel-id).

Thank you!

**Comment by esevan** [comment] 2019-03-30 07:37
@kevin-bates In our use case, user can have multiple `Volumes` and `Mounts`. Even some users don't have any specific volume. Also by deployment target, some options should be on/off configured and those should be represented/commented in `kernel-pod.yaml`; ex) we provide pods using specific resource by adding `tolerations` into kernel `pod` spec. We resolve those issues by modifying `launch_kubernetes.py`, but I believe that it is nothing but a workaround.

If we choose jinja2 as a solution, our `kernel-pod.yaml` will be like following `kernel-pod.yaml.j2`.
This would be formatted by `jinja2` python package, and can be used directly to create pod via `k8s client`. Note that this is a just sample, not tested.
```kernel-pod.yaml.j2
apiVersion: v1
kind: Pod
metadata:
  name: {{ kernel_pod_name }}
  namespace: {{ kernel_namespace }}
  labels:
    kernel_id: {{ kernel_id }}
    app: enterprise-gateway
    component: kernel
spec:
  restartPolicy: Never
  serviceAccountName: {{ kernel_service_account_name }}
{% if kernel_uid is defined %}
  securityContext:
    runAsUser: "{{ kernel_uid }}"
    runAsGroup: "{{ kernel_gid }}"
    fsGroup: 100
{% endif % }
  containers:
  - env:
    - name: EG_RESPONSE_ADDRESS
      value: {{ eg_response_address }}
    - name: KERNEL_LANGUAGE
      value: {{ kernel_language }}
    - name: KERNEL_SPARK_CONTEXT_INIT_MODE
      value: {{ kernel_spark_context_init_mode }}
    - name: KERNEL_NAME
      value: {{ kernel_name }}
    - name: KERNEL_USERNAME
      value: {{ kernel_username }}
    - name: KERNEL_ID
      value: {{ kernel_id }}
    - name: KERNEL_NAMESPACE
      value: {{ kernel_namespace }}
    image: {{ kernel_image }}
    name: {{ kernel_pod_name }}
{% if kernel_working_dir is defined %}
    workingDir: {{ kernel_working_dir }}
{% endif %}
{% if volumeMounts is defined %}
    volumeMounts:
    {% for volumeMount in volumeMounts %}
    - mountPath: {{ volumeMount.mountPath }}
      name: {{ volumeMount.volumeName }}
    {% endfor %}
{% endif %}
{% if volumes is defined %}
  volumes:
  {% for volume in volumes %}
  - name: {{ volume.name }}
    {{ volume.body }}
  {% endfor %}
{% endif %}
```

**Comment by kevin-bates** [comment] 2019-03-30 14:57
This is very encouraging. I think if the result of the substitution is persisted on disk (see the PR I referenced) then I believe we're good from a spark standpoint. EG would perform the cleanup (also in the PR).
Thank you!

**Comment by esevan** [comment] 2019-03-30 15:55
The result of substitution is a `str`, and easily dump into the disk as your reference. Nothing would change but templating logic. Thumbs up?

**Comment by kevin-bates** [comment] 2019-04-06 16:51
I believe #629 addresses the variability issue - among other things.  Closing.

**Closed by kevin-bates** 2019-04-06 16:51 UTC
Labels: Discussion, Kubernetes, Multiuser support
