### ISSUE TITLE
Restart of the kernel does not reconnects stdin channel

### ISSUE THREAD

**Issue by dchirikov** [jupyter/enterprise_gateway#756] opened 2019-11-22 21:34 UTC
## Description

If the menu item "Restart kernel" is pressed in JupyterLab, the frontend loses connection to the kernel. After "restart" cells never return output.

I am playing with a custom class (derived from RemoteProcessProxy), but I am able to reproduce the issue with DistributedProcessProxy.

## Screenshots / Logs

From what I see from the logs on a start there are connections to all set of ports, while on restart hb and stdin is never being reconnected.
Start:
```
[D 2019-11-22 22:26:32.415 EnterpriseGatewayApp] Received connection info for KernelID '37d6233c-bae3-4ab0-8f91-365581b0bfd7' from host 'dc-c7u5': {'shell_port': 48838, 'iopub_port': 45250, 'stdin_port': 34335, 'control_port': 41070, 'hb_port': 49048, 'ip': '10.141.255.254', 'key': '0190b74b-342d-40b3-9514-9fb5f8a5a785', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'comm_port': 54264}...
[D 2019-11-22 22:26:32.416 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:41070
[D 2019-11-22 22:26:32.418 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:45250
[I 2019-11-22 22:26:32.420 EnterpriseGatewayApp] Kernel started: 37d6233c-bae3-4ab0-8f91-365581b0bfd7
[D 2019-11-22 22:26:32.420 EnterpriseGatewayApp] Kernel args: {'env': {'PATH': '/cm/shared/apps/jupyter/6.0.0/bin:/cm/shared/apps/cm-npm-configurable-http-proxy/4.0.1/bin:/cm/local/apps/python37/bin:/cm/local/apps/cm-setup/bin:/cm/local/apps/cluster-tools/bin:/cm/local/apps/cmd/sbin:/cm/local/apps/cmd/bin:/cm/local/apps/environment-modules/4.2.1//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/cm/local/apps/environment-modules/4.2.1/bin:/bin:/sbin:/root/bin:/tmp/.dmitry.sshrc.WkYa', 'KERNEL_LAUNCH_TIMEOUT': '40', 'KERNEL_WORKING_DIR': '/home/cmsupport', 'KERNEL_USERNAME': 'cmsupport'}, 'kernel_name': 'python_slurm'}
[D 2019-11-22 22:26:32.834 EnterpriseGatewayApp] Opening websocket /api/kernels/37d6233c-bae3-4ab0-8f91-365581b0bfd7/channels
[D 2019-11-22 22:26:32.834 SingleUserNotebookApp handlers:155] Connection is ready: ws: <tornado.websocket.WebSocketClientConnection object at 0x2aaabe471b00>
[D 2019-11-22 22:26:32.834 EnterpriseGatewayApp] Getting buffer for 37d6233c-bae3-4ab0-8f91-365581b0bfd7
[D 2019-11-22 22:26:32.834 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:48838
[D 2019-11-22 22:26:32.835 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:41070
[D 2019-11-22 22:26:32.835 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:45250
[D 2019-11-22 22:26:32.836 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:34335
[D 2019-11-22 22:26:32.838 EnterpriseGatewayApp] activity on 37d6233c-bae3-4ab0-8f91-365581b0bfd7: status (busy)
[D 2019-11-22 22:26:32.840 EnterpriseGatewayApp] activity on 37d6233c-bae3-4ab0-8f91-365581b0bfd7: status (idle)
```
Restart:
```
[D 2019-11-22 22:27:47.316 EnterpriseGatewayApp] Received connection info for KernelID '37d6233c-bae3-4ab0-8f91-365581b0bfd7' from host 'dc-c7u5': {'shell_port': 47612, 'iopub_port': 59026, 'stdin_port': 43679, 'control_port': 56182, 'hb_port': 58337, 'ip': '10.141.255.254', 'key': 'bc692a35-da80-4223-a30b-84601cb6c043', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'comm_port': 37503}...
[D 2019-11-22 22:27:47.316 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:56182
[D 2019-11-22 22:27:47.317 EnterpriseGatewayApp] Clearing buffer for 37d6233c-bae3-4ab0-8f91-365581b0bfd7
[D 2019-11-22 22:27:47.318 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:59026
[D 2019-11-22 22:27:47.320 EnterpriseGatewayApp] Refreshing kernel session for id: 37d6233c-bae3-4ab0-8f91-365581b0bfd7
[I 2019-11-22 22:27:47.321 EnterpriseGatewayApp] Kernel restarted: 37d6233c-bae3-4ab0-8f91-365581b0bfd7
[D 2019-11-22 22:27:47.321 EnterpriseGatewayApp] Connecting to: tcp://10.141.255.254:47612
[D 2019-11-22 22:27:47.479 EnterpriseGatewayApp] activity on 37d6233c-bae3-4ab0-8f91-365581b0bfd7: status (busy)
[D 2019-11-22 22:27:47.480 EnterpriseGatewayApp] activity on 37d6233c-bae3-4ab0-8f91-365581b0bfd7: status (idle)
[D 2019-11-22 22:27:47.480 EnterpriseGatewayApp] Kernel info reply received: 37d6233c-bae3-4ab0-8f91-365581b0bfd7
[D 2019-11-22 22:27:47.482 SingleUserNotebookApp managers:461] Restart kernel response: 200 OK
```

`netstat` also shows a reduced set of opened connections.

## Environment
jupyter-client==5.3.4
jupyter-core==4.6.1
jupyter-enterprise-gateway==2.0.0
jupyter-kernel-gateway==2.4.0
jupyterhub==1.0.0
jupyterlab==1.1.4
jupyterlab-server==1.0.6
ipykernel==5.1.3
ipython==7.9.0

OS: Centos 7

**Comment by kevin-bates** [comment] 2019-11-22 22:31
Hmm, I'm unable to reproduce this with either DistributedProcessProxy or YarnClusterProcessProxy.  I've included a [Quicktime movie of the former](https://github.com/jupyter/enterprise_gateway/files/3881667/DistributeProcessProxyRestart.mov.zip) in case that helps (i.e., we're doing different things, etc.).

Are you restarting while a cell is running?  I suspect that would indeed drop the output since that is tantamount to a new connection - which is a known issue in Jupyter (not EG).  In this case, are subsequent cells producing output after restart?

**Comment by dchirikov** [comment] 2019-11-22 23:26
Funny. It works in Jupyter for me too (/tree), but not in JupyterLab (/lab),

**Comment by kevin-bates** [comment] 2019-11-22 23:47
Whoa - interesting, yet disturbing!  Do you know if this happens with local kernels in Lab?  I'd be surprised, but its worth asking.

**Comment by kevin-bates** [comment] 2019-11-22 23:52
Actually, when I change my url to from `/tree` to `/lab`, I still can reproduce the issue and its definitely using lab...
![image](https://user-images.githubusercontent.com/22599560/69468152-f43d9a00-0d3f-11ea-8eea-4f4244341992.png)
You can see the restart between cells 2 and 3 due to the restart of the cell numbers.

**Comment by dchirikov** [comment] 2019-11-25 16:48
Have no issues restarting local kernels, but always get lost kernel with EG. Attaching 2 logs - one for jupyter lab and another one for the classical notebook.
[jl-restart.log](https://github.com/jupyter/enterprise_gateway/files/3887696/jl-restart.log)
[nb-restart.log](https://github.com/jupyter/enterprise_gateway/files/3887697/nb-restart.log)

**Comment by kevin-bates** [comment] 2019-11-25 18:24
Thanks for the logs Dmitry.  It looks like in the lab case, there's never an attempt to initialize the websocket connection following the restart.  The kernel is restarting correctly and the kernel-info-reply is received, but the front end is never initializing the websocket connection.

When I run lab, I see the following in that area of the restart sequence...
```
[I 191125 09:51:28 web:2162] 200 POST /api/kernels/2d61a365-6cf6-4bbe-800c-89fd42c1f67b/restart (9.160.97.99) 3097.94ms
[I 191125 09:51:28 web:2162] 200 GET /api/kernels/2d61a365-6cf6-4bbe-800c-89fd42c1f67b (9.160.97.99) 1.01ms
[I 191125 09:51:28 web:2162] 200 GET /api/kernels/2d61a365-6cf6-4bbe-800c-89fd42c1f67b (9.160.97.99) 0.95ms
[D 2019-11-25 09:51:29.007 EnterpriseGatewayApp] Initializing websocket connection /api/kernels/2d61a365-6cf6-4bbe-800c-89fd42c1f67b/channels
[W 2019-11-25 09:51:29.008 EnterpriseGatewayApp] No session ID specified
[I 2019-11-25 09:51:29.009 EnterpriseGatewayApp] Adapting to protocol v5.1 for kernel 2d61a365-6cf6-4bbe-800c-89fd42c1f67b
[I 191125 09:51:29 web:2162] 101 GET /api/kernels/2d61a365-6cf6-4bbe-800c-89fd42c1f67b/channels (9.160.97.99) 3.40ms
[D 2019-11-25 09:51:29.009 EnterpriseGatewayApp] Opening websocket /api/kernels/2d61a365-6cf6-4bbe-800c-89fd42c1f67b/channels
[D 2019-11-25 09:51:29.010 EnterpriseGatewayApp] Getting buffer for 2d61a365-6cf6-4bbe-800c-89fd42c1f67b
[D 2019-11-25 09:51:29.010 EnterpriseGatewayApp] Clearing buffer for 2d61a365-6cf6-4bbe-800c-89fd42c1f67b
[D 2019-11-25 09:51:29.010 EnterpriseGatewayApp] Connecting to: tcp://172.16.18.99:58128
[D 2019-11-25 09:51:29.011 EnterpriseGatewayApp] Connecting to: tcp://172.16.18.99:60084
[D 2019-11-25 09:51:29.011 EnterpriseGatewayApp] Connecting to: tcp://172.16.18.99:37507
```

One thing I'm doing relative to my lab is that in either case (notebook and lab), I run `jupyter notebook` but change my url from `host:port/tree` to `host:port/lab`.  Are you doing similarly or are you running `jupyter lab` directly. 

Hmm, when I run `juptyer lab` directly (e.g., `jupyter lab --gateway-url=http://yarn-eg-node-1.fyre.ibm.com:8888 --debug --notebook-dir=~/notebooks/alice`) I can reproduce the issue since I don't see an attempt to initialize the websocket.  So this appears to be an issue with how the lab extension is "started".

@jasongrout - Per the information above, can you think of why restarts (in this case they tend to be remote kernels, but that shouldn't make a difference) would be affected by how the lab extension is "instantiated".  I don't know the differences between starting `jupyter notebook` and switching the url from `/tree` to `/lab`, vs. starting `jupyter lab` directly.

Since local kernels work in lab, are there any assumptions in the pure lab instantiation case that would perhaps attempt to initialize the websocket in a different manner than notebook-based instantiation?  Any info would be helpful.

@dchirikov - would you mind starting notebook, then switching to the `/lab` root and see if your restarts succeed again?  Just want to make sure we're all seeing the same thing.

**Comment by dchirikov** [comment] 2019-11-25 21:24
@kevin-bates Thank you for trying and not closing "it works on my machine" :)
For me it reproducible in both ways. Whether I start `jupyter lab` or `jupyter notebook` and then switching to `/lab`. But indeed I see no attempts to fetch websocket info in logs.

**Comment by kevin-bates** [comment] 2019-12-05 15:49
@dchirikov - I wanted to let you know that I don't have any bandwidth to look into this right now.  I think the best approach would be to first determine if there are differences between the restart sequences in Notebook and JupyterLab and, if so, why Lab's sequence doesn't reconnect `stdin` via EG.

@jasongrout - are you able to point Dmitry to the kernel restart logic in Notebook and Lab?  Thanks.

**Comment by jasongrout** [comment] 2020-03-09 20:01
FYI, the connection logic was rewritten in JupyterLab 2.0. Do you still see this problem in JupyterLab 2.0.x?

**Comment by ms-lolo** [comment] 2020-04-16 17:53
I am still seeing this issue with JupyterLab 2.1.0

**Comment by kevin-bates** [comment] 2020-04-16 17:58
@ms-lolo - I'm sorry to hear this.  Do you only see with restart behavior when using Enterprise Gateway?  What resource manager are you using (YARN, Kubernetes, etc.)? Or are you using EG with only local kernels?

**Comment by ms-lolo** [comment] 2020-04-16 20:22
I'm using JupyterHub → JupyterLab → Enterprise Gateway → Kubernetes Kernels. I built my own Kernel docker images so I was half hoping this was user error on my side but I'm still not comfortable enough with the entire stack to troubleshoot easily.

Seems the kernel starts back up properly but the UI never connects to the new instances.

**Comment by kevin-bates** [comment] 2020-04-16 20:38
ok - thanks.  Could you please enable DEBUG on your EG instance (restart required), then capture the complete log of the kernel interaction, from initial startup through the completion of the restart?  I'd like to take a look at that.

After reviewing this thread, it's sounding like there may be something with how the lab extension starts.  Could you also please launch `jupyter notebook` and then switch between /tree and /lab endpoints and see how restarts behave in each?  If you also find that restarts work in `jupyter notebook {/tree, /lab}` this might be something in lab, but I'd have no idea how to describe it other than I wonder if there's some kernel-locality assumption (that it's local) that isn't happening on restarts.

**Comment by ms-lolo** [comment] 2021-03-04 05:07
hey folks! just wanted to mention that this doesn't seem to be a problem for us any more since upgrading to lab 3.x. not sure if this is good to close or if other folks are still having trouble.

Cheers!

**Comment by kevin-bates** [comment] 2021-03-04 15:38
@ms-lolo - thank you for returning to update this issue - that is greatly appreciated!  I suspect that the changes in https://github.com/jupyterlab/jupyterlab/pull/9388 resolved this.  Since it looks like @cceyda gave your comment a +1, and I noticed their presence on a related issue, I suspect we're good to close this.

Thanks everyone for helping with this.

**Closed by kevin-bates** 2021-03-04 15:38 UTC
Labels: Bug, JupyterLab

**Comment by dchirikov** [comment] 2021-03-04 17:56
Can confirm, the issue is gone! :+1:

**Comment by kevin-bates** [comment] 2021-03-04 18:10
Excellent - thank you @dchirikov!
