### ISSUE TITLE
Kernel goes into restart loop 

### ISSUE THREAD

**Issue by Gsbreddy** [jupyter/enterprise_gateway#621] opened 2019-03-27 14:44 UTC
Hi all,

I am running a code snippet which uses boto and connects to s3. But when I run pandas.read_csv() I am getting the following error and kernel goes into restart loop. Any ideas on this?

`[E 190327 03:57:36 ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(f171a0eb-3c12-4238-a542-1469c9f679da)>
    Traceback (most recent call last):
      File "/opt/python/python35/lib/python3.5/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/opt/python/python35/lib/python3.5/site-packages/notebook/base/zmqhandlers.py", line 189, in send_ping
        self.ping(b'')
      File "/opt/python/python35/lib/python3.5/site-packages/tornado/websocket.py", line 447, in ping
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError`

`[E 190327 03:57:36 ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(f171a0eb-3c12-4238-a542-1469c9f679da)>
    Traceback (most recent call last):
      File "/opt/python/python35/lib/python3.5/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/opt/python/python35/lib/python3.5/site-packages/notebook/base/zmqhandlers.py", line 189, in send_ping
        self.ping(b'')
      File "/opt/python/python35/lib/python3.5/site-packages/tornado/websocket.py", line 447, in ping
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError`

`[E 190327 03:57:36 ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(f171a0eb-3c12-4238-a542-1469c9f679da)>
    Traceback (most recent call last):
      File "/opt/python/python35/lib/python3.5/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/opt/python/python35/lib/python3.5/site-packages/notebook/base/zmqhandlers.py", line 189, in send_ping
        self.ping(b'')
      File "/opt/python/python35/lib/python3.5/site-packages/tornado/websocket.py", line 447, in ping
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError`

**Comment by kevin-bates** [comment] 2019-03-27 15:42
I've not seen this.  I'm curious if you see the same thing using vanilla Notebook, but I suppose your kernel is running remotely in a cluster - correct?  If so, are you able to reproduce using Notebook with a non-clustered kernel?  

Since everything is lower than EG, you might get better traction via Notebook since this doesn't strike me as anything EG specific.  Is anything logged in the Notebook log/output that is configured with NB2KG?

**Comment by kevin-bates** [comment] 2019-04-05 14:37
@Gsbreddy - You might also make sure you're running Tornado >= 6 and NB >= 5.7.6.

**Comment by kevin-bates** [comment] 2019-04-22 20:51
Closing.  I you disagree, please re-open and provide additional information.  Thanks.

**Closed by kevin-bates** 2019-04-22 20:51 UTC
