### ISSUE TITLE
Kernel Launch Timeout

### ISSUE THREAD

**Issue by srroh1** [jupyter/enterprise_gateway#745] opened 2019-10-14 15:07 UTC
Getting below issue when we are trying to launch Kernel from Jupyter notebook, getting timeout on Tornado HTTP client, Can someone kindly help on this issue.

We tried increasing below values in env file didn't help 

    "EG_KERNEL_LAUNCH_TIMEOUT": "600",
    "EG_SOCKET_TIMEOUT": "600",
    "KERNEL_LAUNCH_TIMEOUT": "600",

We checked in YARN UI  , no jobs are running in YARN lots of queue resource are also available 

Issue gets resolving whenever Jupyter Hub restarts but we are looking for permanent solution 

Here is the version details :
jupyter_enterprise_gateway 1.2.0 
jupyterhub 0.9.4 
jupyter_core  4.4.0 
Jupyter_client- 5.2.4 
jupyterhub 0.1.1
tornado- 6.0.1

python3[3079573]: value = future.result()
python3[3079573]: tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
 python3[3079573]: [W 2019-10-14 09:39:23.835 SingleUserNotebookApp handlers:620] Unhandled error
 python3[3079573]: [E 2019-10-14 09:39:23.835 SingleUserNotebookApp log:150] {

tornado.httpclient.HTTPClientError: HTTP 500: KernelID: '18f5dcad-ba5f-47a3-b20a-b0a20cdec17e' launch timeout due to: Application ID is None. Failed to submit a new application to YARN within 30.0 seconds. Check Enterprise Gateway log for more information

**Comment by lresende** [comment] 2019-10-14 15:22
@srroh1 Just transferred your issue as this is an Enterprise Gateway related issue.

**Comment by kevin-bates** [comment] 2019-10-14 15:43
Hi @srroh1 - these kinds of issues are usually due to configuration or resources.  Got a couple questions: 
1. Have you successfully launched a kernel in this YARN environment previously?  (If yes, this tends to point to resources)
2. Have you inspected both the EG log and the YARN logs for the kernel being launched?

Please ensure DEBUG is enabled in your EG configuration.  Once that is confirmed, reproduce the issue and attach the complete EG log file.  If you can access the YARN logs, the stdout and stderr logs are usually the most helpful.  I will be happy to review whatever information you can provide.

**Comment by srroh1** [comment] 2019-10-14 18:06
@kevin-bates  I'm able to launch YARN application after jupyter services has been restarted, within 4 to 5 hours we are keep getting kernel errors not able to launch YARN application .we setup to log with native systemd logs we are navigating logs with journalctl that's all information we can see.

As you said what could be the configurations we need to validate as part of kernel errors
On other Hand Resource wise its plentiful its 1000+ node cluster lots of resource are available

**Comment by kevin-bates** [comment] 2019-10-14 18:47
ok, so things run fine for 4 to 5 hours, then you're unable to launch kernels into YARN?

What is the nature of the errors you do see in the EG log?

Based on the information you've provided, it looks like you're using JupyterHub, launching notebook servers, that are then configured to hit an EG server - is that correct?

Btw, I suspect you updated KERNEL_LAUNCH_TIMEOUT to 600 in the EG instance.  Since this "flows" from the client, it needs to be configured in the Notebook instance.  However, it should also be **less than** the KG_REQUEST_TIMEOUT and KG_CONNECT_TIMEOUT values.  So you should look into increasing those if you'd like a larger KERNEL_LAUNCH_TIMEOUT.  I'd try something on the order of 120 seconds, rather than 10 minutes as well.

EG_SOCKET_TIMEOUT is probably not coming into play here and EG_KERNEL_LAUNCH_TIMEOUT is more of a global default in cases where the client doesn't provide KERNEL_LAUNCH_TIMEOUT.  Unfortunately, I believe we now always set KERNEL_LAUNCH_TIMEOUT in NB2KG or Notebook --gateway-url, so this "default" doesn't come into play either.

**Comment by srroh1** [comment] 2019-10-14 21:17
@kevin-bates 
1. ok, so things run fine for 4 to 5 hours, then you're unable to launch kernels into YARN?
   Yes 

2. What is the nature of the errors you do see in the EG log? 
  As you said we enabled DEBUG logs for EG restarted the service we have to wait next couple hours   to get error logs (reproducing the issue).will post error message once its start appearing 

3.Based on the information you've provided, it looks like you're using JupyterHub, launching notebook servers, that are then configured to hit an EG server - is that correct?
   Yes 

4. Can you please specify were we need to update KERNEL_LAUNCH_TIMEOUT value in notebook instance client side (we have modified kernel parameters under this location for both python 2 and python 3 /usr/share/jupyter/kernels/python2/kernel.json) Thanks for recommending to set this value to 120 seconds we just keep it 600 sec for testing purpose. 

What is propose of KG_REQUEST_TIMEOUT , KG_CONNECT_TIMEOUT where we need to change these values ?

**Comment by kevin-bates** [comment] 2019-10-14 21:41
> What is propose of KG_REQUEST_TIMEOUT , KG_CONNECT_TIMEOUT where we need to change these values ?

Those values come into play on the http requests (in reality - only kernel startup since it can take so long) between the notebook and the gateway.  The gateway has no knowledge of their values.  If you're using Notebook 6 with `--gateway-url` they default to 60 seconds, while KERNEL_LAUNCH_TIMEOUT defaults to 40. 

Sorry, I forgot that their names will vary depending on how you're talking to the gateway.  
If using `--gateway-url`, they are: https://github.com/jupyter/notebook/blob/master/notebook/gateway/managers.py#L105-L122
If using NB2KG, they are: https://github.com/jupyter/nb2kg/blob/master/nb2kg/managers.py#L37-L38

**Comment by srroh1** [comment] 2019-10-15 15:37
I guess I found the issue after enabling DEBUG logs for EG , Juypter-enterprisegateway is not renewing the Kerberos ticket to submit the Kernel to YARN , is it know issue ?

Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: 19/10/15 09:17:43 WARN Client: Couldn't setup connection for elyra/hostname@realm to hostname/10.xx.xx.xx:8032
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:408)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:614)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:410)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:800)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:796)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at java.security.AccessController.doPrivileged(Native Method)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at javax.security.auth.Subject.doAs(Subject.java:422)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:796)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:410)
Oct 15 09:17:43 hostname jupyter-enterprisegateway[699520]: at org.apache.hadoop.ipc.Client.getConnection(Client.java:1558)
~

**Comment by srroh1** [comment] 2019-10-15 18:25
@kevin-bates  Thanks for pointing this issue #491 , Is there any near fix for this ?

**Comment by kevin-bates** [comment] 2019-10-15 18:31
> I don't believe anyone is looking into this right now.

Don't know of a workaround either - other than extending ticket lifetimes or restarting.  Sorry.

**Comment by srroh1** [comment] 2019-10-16 14:46
@kevin-bates  Thanks for your help !!

Can you please point me to the code where gateway requires keytab renewing step , we will try patching it.

Thanks

**Comment by kevin-bates** [comment] 2019-10-16 16:42
@srroh1 - thank you for taking a look into this!  

EG doesn't actually do anything with kerberos or the ticket.  The fact that kerberos is in use is conveyed to EG via the [`yarn_endpoint_security_enabled` configuration value](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/enterprisegatewayapp.py#L296-L298).  In 2.0, this boolean is then passed into the [YARN client api](https://github.com/toidi/hadoop-yarn-api-python-client) - which essentially just passes that information to YARN.  In the current tip, [this boolean triggers the instantiation of an HTTPKerberosAuth instance](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/yarn.py#L61-L65).  (At that same time, the yarn-api-client library went through some major changes.  So you'll need appropriate yarn-api-client versions)

At any rate, I believe the place where a periodic callback trigger would be warranted, would be in the `enterprisegatewayapp.py` file itself.  Based on the boolean value, it seems like this would be located somewhere near [this code](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/enterprisegatewayapp.py#L624).

Here's an example of [setting up a periodic callback](https://github.com/jupyter/notebook/blob/master/notebook/services/kernels/kernelmanager.py#L435-L436) - this is used to cull idle kernels.  

Now that I think about it, given that I don't know anything about working with keytab files, etc., using a periodic callback may not be the way to go, although it seems like EG needs to renew tickets, so I have to believe its _part_ of the solution.

cc: @jcrist - I'm hoping Jim might also be able to lend some guidance here. (wink, wink)

**Comment by kevin-bates** [comment] 2020-01-03 20:28
Closing since this issue wound up being related to kerberos ticket renewal - which is discussed in #491.

**Closed by kevin-bates** 2020-01-03 20:28 UTC
Labels: YARN
