### ISSUE TITLE
Enable open terminal connected to the kernel

### ISSUE THREAD

**Issue by esevan** [jupyter/enterprise_gateway#557] opened 2019-01-21 08:00 UTC
Hi, `enterprise_gateway` provides great experience in terms of resource utilization.
Multiple kernels are up at the same time and on different nodes.

As a result of splitting host running a kernel from the notebook host, however, the terminal is open only in the notebook host. For me, I sometimes want to open terminal in kernel and run the source code in terminal directly.

What do you think about this feature? Is it obvious to open the terminal in notebook host? or should it be open in kernel host as well?

**Comment by kevin-bates** [comment] 2019-01-21 14:52
I'm not sure what the expected behavior should be.  If kernels are distributed across a cluster by virtue of a resource manager, what does it mean to open a terminal _on the kernel host_?  I can understand using a terminal when kernel hosts are static, but EG is all about distribution - so how useful would it be to open a terminal window on a host that is essentially random.  As a result, there would need to be some association established between the terminal that is about to be launched and existing kernel instances - so I think the kernel would need to come first to establish the target host.  

I haven't looked at the terminal code, but I suspect it would require plumbing to get the terminal request over to the gateway server, in addition to the code to match it up to a kernel.  I see lab has console windows and those appear to essentially be just another connection to the running kernel.  I think any kind of terminal implementation would need to do something similar.

**Comment by esevan** [comment] 2019-01-22 00:10
I'm using the kernels which have their own resource specifications (like 4cpu & 1gpu size pod for tensorflow gpu kernel, 1cpu size pod for python kernel) and allocating just little resource for jupyter lab.

I'm not sure how my case is common, but I can't run python code via terminal in that case due to lacking of libs and resources of jupyterLab pod.

If this usecase is reasonable, jupyter lab extension for enterprise gateway can be considered to implement to cover remote terminal and lab extension could be a solution for #555.

I appreciate any opinions!

**Comment by kevin-bates** [comment] 2019-01-22 00:50
Thanks for the update.  I don't really know anything about terminal or the use cases it's meant to address.  I'm also unfamiliar with nb/lab extensions, so have no idea what would be involved, although I would guess it's a substantial effort if it doesn't already leverage the kernel api - like the console stuff must.

However, again, I don't know how you're going to figure out the host that a particular kernel is running on and I don't think we want to "go there".

@lresende - you've dabbled in lab extensions, do you have any thoughts here?

**Comment by kevin-bates** [comment] 2019-02-06 15:32
@esevan - You might be interested in #571.  With appropriate volume mounts, this essentially provides a means of having the kernel images track the notebook working directories.  Since terminal is local to the notebook server, you could still _adjust_ resources via terminal which should be available to the kernel container provided those adjustments occur on the same volume.

Might this help your scenario?

**Comment by esevan** [comment] 2019-02-07 03:28
@kevin-bates Thanks, it absolutely helps. Most of my workarounds have ended with that commit.

After first quarter, when some of busy things not related to jupyter are finished, I'm looking forward to contributing to this project. thanks again for immediate response.

**Comment by kevin-bates** [comment] 2019-02-07 14:39
That's great new @esevan - we look forward to working with you!

If you feel #571 addresses the terminal issue, please go ahead and close this issue.

**Closed** 2019-02-08 09:58 UTC
Labels: Discussion

**Comment by elgalu** [comment] 2020-11-21 04:56
IMHO #571 doesn't address the Terminal issue. In SageMaker Studio, for instance, one can open a Terminal inside the execution environment (in this case a docker container) that the notebook runs, this allows you to do shell tasks like nvidia-smi or whatever system debugging you need to do more comfortably. In the case of K8s this would mean being able to open a Terminal in the K8s pod that the remote kernel is running.

**Comment by kevin-bates** [comment] 2020-11-21 18:06
Hi @elgalu - thanks for the comment.  

The terminal capability exposed in Notebook and Lab opens the terminal relative to the notebook server, not the kernel.  We have no plans on having terminado run in the kernel's pod since that's is a completely different mechanism.  I'm sure SageMaker is just leveraging the same functionality and, because they happen to deploy an actual notebook server in K8s (just as Jupyter Hub does), the terminal is running on the Notebook server and is completely independent of kernels launched - which will also run in that same pod - unlike kernels launched from EG.

There is also no way to associate an instance of Terminal with a particular kernel, which again, in the case of EG could consist of several kernels all distributed across the cluster.  So there would be several differences to resolve to address this kind of functionality.

The idea behind #571 is that one _could_ appropriately configure mounts such that a terminal could be run that has access to those same _mounts_.  However, as you point out, that terminal will not have access to the actual runtime environment shared by the (remote) kernel.
