### ISSUE TITLE
does EG support IPV6 and in turn the kernels?

### ISSUE THREAD

**Issue by suryag10** [jupyter/enterprise_gateway#874] opened 2020-09-10 07:03 UTC
Hi We are trying to deploy the Jupyter EG in K8S IPV6 environment. Does EG support IPV6 and in turn the kernels?

**Comment by kevin-bates** [comment] 2020-09-10 14:06
Hi @suryag10 - this is a duplicate of #428.  Your help would be much appreciated.  Closing as duplicate.

**Closed by kevin-bates** 2020-09-10 14:06 UTC
Labels: Duplicate
