### ISSUE TITLE
How to specify the auth token for use by image puller

### ISSUE THREAD

**Issue by camer314** [jupyter/enterprise_gateway#956] opened 2021-04-26 02:30 UTC
I am using EG on Kubernetes and have configured it to run with an auth token. However the image puller is getting 401 errors because it is not passing the token along with its requests to list kernels.

How can I configure the image puller to pass a token? I dont see any obvious environment variable.

**Comment by kevin-bates** [comment] 2021-04-26 15:04
Could you please provide more details as to how you're configuring the auth token for EG as well as the log from a failed image puller request?  If there is any log data produced in the EG pod, providing that might prove useful as well.  Thanks.

I suspect some kind of secret would need to be configured that are shared between the two.

cc: @akchinSTC

**Comment by camer314** [comment] 2021-04-26 22:25
HI @kevin-bates 

I am configuring the auth token for EG in the deployment.yaml file (as EG_AUTH_TOKEN) and then in the values.yaml I am hardcoding a token, e,g

authToken: XXXX

- name: EG_AUTH_TOKEN   
          value: {{ .Values.authToken }}

I am then starting a notebook like so

jupyter notebook --gateway-url=http://<ip>/gateway --GatewayClient.auth_token=XXXX

And that all works fine. However the image-puller pod is unable to list kernels when an auth token is configured because it does not add the token to the query or the header when it makes the request. I dont have my Kubernetes environment at the moment but for sure it was getting a 401 and only started working when i turned off auth tokens.

So i think the issue is the image-puller needs to support a token and then pass that through to the gateway. I am also using the JupyterLab/Services JavaScript SDK and need to do that as when communicating with the EG.

You already have these variables for the image puller, so maybe just add KIP_AUTH_TOKEN?

env:
          - name: KIP_GATEWAY_HOST
          - name: KIP_INTERVAL
          - name: KIP_PULL_POLICY

**Comment by kevin-bates** [comment] 2021-04-26 23:22
@camer314 - thank you for the excellent information.  Yes, that sounds exactly like what we'd need to do.

Would you like to give that a go?

**Comment by camer314** [comment] 2021-04-27 04:22
Thanks @kevin-bates 

I would contribute however the contributions page does not exist :) https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html and I am also unable to build the gateway on Windows

However, I did make the necessary changes and rebuilt the docker image, added  the necessary config to helm chart, pointed KIP to my image and its all now working as expected...

[kernel_image_puller.zip](https://github.com/jupyter/enterprise_gateway/files/6381794/kernel_image_puller.zip)

**Comment by kevin-bates** [comment] 2021-04-27 14:50
Sorry about that.  Looks like Jupyter moved the contributor page to _contributing_: https://jupyter.readthedocs.io/en/latest/contributing/content-contributor.html

We don't officially support Windows as EG has never been qualified on that platform, so, yeah, I'm not surprised there are issues there.

Looking at the changes, they look fine.  Would you mind composing a pull request and we'll move foward with a review and merge?  Thank you!

**Comment by camer314** [comment] 2021-04-28 01:49
Done

**Comment by kevin-bates** [comment] 2021-04-28 17:47
Hi @camer314 - thank you for the corresponding pull request #959.  We typically close corresponding issues via GitHub's [keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) framework referenced in pull request.  This way, the issue is only closed once the PR is merged.  Please add a 'Fixes #956` line in your pull request's description body (preferably along with some text describing the changes).

I'm going to re-open this issue and we can work off the PR for now.

**Closed** 2021-10-14 23:04 UTC
