### ISSUE TITLE
There's 5 seconds delay because of the "timed out" when shutdown_kernel is called using KubernetesProcessProxy

### ISSUE THREAD

**Issue by taeyeopkim1** [jupyter/enterprise_gateway#822] opened 2020-06-10 23:44 UTC
### Situation
[As spec in here,](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/etc/kernelspecs/python_kubernetes/kernel.json#L6)
when using "enterprise_gateway.services.processproxies.k8s.KubernetesProcessProxy", 
"shutdown_kernel" method is called, then
"An unexpected exception occurred sending listener shutdown to {} for KernelID {}: timed out" log is printed.
(and 5 seconds delay)

### Cause
After POD is terminated in [line 153](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L153), 
[line 154](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L154) calls socket process for comm_port.

---

To elaborate the call process,

1. RemoteKernelManager class in [line 202](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/kernels/remotemanager.py#L202) inherits IOLoopKernelManager,
IOLoopKernelManager inherits KernelManager.

2. When [shutdown_kernel](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L349) method in KernelManager is called
it calls cleanup method in [line 379](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L379).

3. When self.process_proxy.cleanup() in [line 383](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/kernels/remotemanager.py#L383) is called,
process_proxy is KubernetesProcessProxy in [line 28](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/k8s.py#L28).
KubernetesProcessProxy inherits ContainerProcessProxy,
so it calls cleanup of ContainerProcessProxy in [line 149](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L149)

4. It calls self.kill() in [line 153](
https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L153) and 
self.terminate_container_resources() is called in [line 145](
https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L145).
"terminate_container_resources" in [line 79](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/k8s.py#L79) runs,
it deletes POD using client.CoreV1Api() in [line 103](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/k8s.py#L103).

5. When [line 154](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L154) super(ContainerProcessProxy, self).cleanup() runs,
cleanup in [line 988](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L988) is executed, because RemoteProcessProxy is super class of ContainerProcessProxy,
and self.shutdown_listener() in [line 990](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L990) is executed.

6. The definition for shutdown_listener is in [line 1053](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L1053).
If "comm_port" is setted up ([comm_port > 0](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L1059)),
In [line 1064](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L1064), self._send_listener_request(shutdown_request, shutdown_socket=True) is executed, but because it already deleted POD in 4. [line 103](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/k8s.py#L103),
when _send_listener_request in [line 1064](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L1064) is executed,
it prints out the log "An unexpected exception occurred sending listener shutdown to {} for KernelID {}: timed out" in [line 1068](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L1068).

### Problem
When you look into the [line 42](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/processproxy.py#L42), socket_timeout is setted up for 5 seconds.
This set-up makes it always takes 5 seconds for kernel_shutdown.

### To bypass in current situation
To bypass this problem, I made anotherk8s.py and adjusted kernel.json,
and it processed shutdown without timed out.

enterprise_gateway/services/processproxies/anotherk8s.py

```
from .k8s import KubernetesProcessProxy


class AnotherKubernetesProcessProxy(KubernetesProcessProxy):
  def terminate_container_resources(self):
    result = super(AnotherKubernetesProcessProxy, self).terminate_container_resources()
    self.comm_port = 0
    return result    
```
and adjust [line 6](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/etc/kernelspecs/python_kubernetes/kernel.json#L6) as
```
"class_name": "enterprise_gateway.services.processproxies.anotherk8s.AnotherKubernetesProcessProxy"
```

### Solution suggestion
It seems like inheriting ContainerProcessProxy is only
KubernetesProcessProxy in k8s.py  
DockerSwarmProcessProxy in docker_swarm.py

so I can adjust [line 153](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L153) and [line 154](https://github.com/jupyter/enterprise_gateway/blob/v2.1.1/enterprise_gateway/services/processproxies/container.py#L154) into

```
def cleanup(self):
	# Since container objects don't necessarily go away on their own, we need to perform the same
	# cleanup we'd normally perform on forced kill situations.
	
	super(ContainerProcessProxy, self).cleanup()
	self.kill()
```

I suggest this would be better.
What do you think of this adjust?

## Screenshots / Logs

```
[D 2020-06-10 12:06:39.229 EnterpriseGatewayApp] Clearing buffer for c4ff6536-2095-4328-9928-3291ef3118fd
[I 2020-06-10 12:06:39.229 EnterpriseGatewayApp] Kernel shutdown: c4ff6536-2095-4328-9928-3291ef3118fd
[D 2020-06-10 12:06:40.670 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: sb.c4ff6536-2095-4328-9928-3291ef3118fd, kernel ID: c4ff6536-2095-4328-9928-3291ef3118fd has been terminated.
[W 2020-06-10 12:06:45.674 EnterpriseGatewayApp] An unexpected exception occurred sending listener shutdown to 66.123.80.2:49705 for KernelID 'c4ff6536-2095-4328-9928-3291ef3118fd': timed out
[I 200610 12:06:45 web:2250] 204 DELETE /api/kernels/c4ff6536-2095-4328-9928-3291ef3118fd (66.123.192.31) 6447.26ms
```

## Environment

- Enterprise Gateway Version [v2.1.1]
- Platform: [Kubernetes]

**Comment by kevin-bates** [comment] 2020-06-11 00:02
Hi @taeyeopkim1 - thank you for this issue and welcome to Enterprise Gateway!

What's funny is I just noticed this exact same problem this afternoon and added it to my notes to look at more closely.  I think this is a side-effect of an earlier change where we're issuing an extra shutdown to the kernel listener and, you're exactly right, this results in an additional 5 seconds (due to the timeout) for the DELETE request to return.

It would be awesome if you want to provide a PR for this!  I would be happy to help you through the "build maze" - but it sounds like you're on top of things.

I'd really like to get 2.2.0rc1 out in the next couple days (or early next week) since Notebook 6.1.0rc1 just became available and we can FINALLY merge #794 to allow async startups.

Please let me know if you're interested in taking a crack at this and I'll go ahead and assign it to you.

Thanks again!

**Comment by taeyeopkim1** [comment] 2020-06-11 00:48
Thanks a lot for your reply.
If you assign it to me, I can provide a PR for this issue.
Please let me know about due date. :)

**Comment by kevin-bates** [comment] 2020-06-11 01:11
Hi @taeyeopkim1 - thank you for the response.

As I look into this a bit, I suspect I introduced a regression on k8s with this PR https://github.com/jupyter/enterprise_gateway/pull/707.

The additional `shutdown_listener()` call was added in [`cleanup()`](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/processproxy.py#L996) and I suspect the pod has been shutdown by that point. 

When I looked briefly at this early, I did confirm that the kernel pod had gotten the shutdown request via the `shutdown_listener()` method, but did not see two of them - thus I think the one from cleanup is not necessary and was leading to the timeout since the pod had terminated.

You can see this here...
```
[I 2020-06-10 22:00:17.136 EnterpriseGatewayApp] Kernel shutdown: b90c122c-deeb-43ba-ad26-a44b04c35c6c
First send -> [D 2020-06-10 22:00:17.139 EnterpriseGatewayApp] Shutdown request sent to listener via gateway communication port.
Pod terminated -> [D 2020-06-10 22:00:18.020 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: jovyan-b90c122c-deeb-43ba-ad26-a44b04c35c6c.jovyan-b90c122c-deeb-43ba-ad26-a44b04c35c6c-1591826342720-driver, kernel ID: b90c122c-deeb-43ba-ad26-a44b04c35c6c has been terminated.
Second send timeout (5 secs later) -> [W 2020-06-10 22:00:23.022 EnterpriseGatewayApp] An unexpected exception occurred sending listener shutdown to 10.47.0.5:39339 for KernelID 'b90c122c-deeb-43ba-ad26-a44b04c35c6c': timed out
[I 200610 22:00:23 web:2250] 204 DELETE /api/kernels/b90c122c-deeb-43ba-ad26-a44b04c35c6c (10.32.0.1) 5891.94ms
```

Your suggestion to add cleanup to ContainerPP still calls the superclass - which would still issue the additional shutdown request (and timeout).

Since I believe this is more of an issue relative to YARN and DistributedPP, I'm thinking it might be best to have me look at this.

**What _would_ be very helpful is if you could just comment out the call to `shutdown_listener()` in `cleanup()` and see if you see the right behavior.**  Then, worst case, I can add cleanup methods on YARNPP and DistributePP that also call shutdown_listener.

(I'm not very good about checking k8s and docker regularly - and I apologize.)

**Comment by taeyeopkim1** [comment] 2020-06-11 02:09
@kevin-bates 
Thanks for a thorough response.
It's a more complicated situation than I thought.
Then I won't provide a PR, and I will just watch this issue.

As you know,
It is difficult to modify original source code in kubernetes (docker) environment.
So.. if I have a chance to comment out the call to `shutdown listener()` in `cleanup()`, I will test it and share the results. (..It can be quite late.)

I hope this issue works out.

**Comment by kevin-bates** [comment] 2020-06-11 02:58
@taeyeopkim1, thank you for your help! I've pushed an [EG image](https://hub.docker.com/r/elyra/enterprise-gateway/tags) with tag `async_822`.  This image is more like an rc0 release since it enables asynchronous kernel management (yet to be merged #794) as well as fix (I hope) #822 for you.

I hope you can check it out and update the issue with how shutdowns turn out - thank you!

**Comment by kevin-bates** [comment] 2020-06-11 14:21
I have a fix for the issue.  I was a bit overzealous with the shutdown listener call in `cleanup()`.  This is necessary for DistributedProcessProxy, but not the others, so I'll be moving that portion of `cleanup()` to `distributed.py`.

I've also confirmed the `elyra/enterprise-gateway:async_822` image yields an appropriate shutdown time with DELETE requests taking around 1.5 secs vs 5+ secs.  So you should probably just use that image for now.

Thanks again for all of your help!

**Comment by taeyeopkim1** [comment] 2020-06-12 05:15
@kevin-bates 
I greatly appreciate all your help.
I tested "async_822" as below, and I'll show you what I did.
It works very well!
 
#### Check enterprise-gateway.yaml
```
image: elyra/enterprise-gateway:async_822
```

#### Check processproxy.py
```
    def cleanup(self):
        """Terminates tunnel processes, if applicable."""
        # This call may be unnecessary for some platforms, checking...
        #self.shutdown_listener()  # Ensure listener has been shutdown

        self.assigned_ip = None

        for kernel_channel, process in self.tunnel_processes.items():
            self.log.debug("cleanup: terminating {} tunnel process.".format(kernel_channel))
            process.terminate()

        self.tunnel_processes.clear()
        super(RemoteProcessProxy, self).cleanup()
```

#### Start kernel
```
# curl -d '{"name":"python_kubernetes"}' -X POST -H "Content-Type: application/json" http://enterprise-gateway.enterprise-gateway:8888/api/kernels

[D 2020-06-12 04:46:52.237 EnterpriseGatewayApp] RemoteMappingKernelManager.start_kernel: python_kubernetes, kernel_username: jovyan
[D 2020-06-12 04:46:52.248 EnterpriseGatewayApp] Instantiating kernel 'Python on Kubernetes' with process proxy: enterprise_gateway.services.processproxies.k8s.KubernetesProcessProxy
[D 2020-06-12 04:46:52.662 EnterpriseGatewayApp] Response socket launched on '10.1.0.101:35523' using 5.0s timeout
[D 2020-06-12 04:46:52.662 EnterpriseGatewayApp] Starting kernel (async): ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', '1c5d6e32-8c59-44e2-8a60-11499cbeb39e', '--RemoteProcessProxy.response-address', '10.1.0.101:35523']
[D 2020-06-12 04:46:52.662 EnterpriseGatewayApp] Launching kernel: Python on Kubernetes with command: ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', '1c5d6e32-8c59-44e2-8a60-11499cbeb39e', '--RemoteProcessProxy.response-address', '10.1.0.101:35523']
[I 2020-06-12 04:46:52.672 EnterpriseGatewayApp] Created kernel namespace: jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e
[I 2020-06-12 04:46:52.683 EnterpriseGatewayApp] Created kernel role-binding 'kernel-controller' in namespace: jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e for service account: default
[D 2020-06-12 04:46:52.683 EnterpriseGatewayApp] BaseProcessProxy.launch_process() env: {'LC_ALL': 'en_US.UTF-8', 'LANG': 'en_US.UTF-8', 'EG_SHARED_NAMESPACE': 'False', 'HOSTNAME': 'enterprise-gateway-7fd9786dcf-pnlcb', 'EG_ENABLE_TUNNELING': 'False', 'KG_PORT_RETRIES': '0', 'NB_UID': '1000', 'EG_LOG_LEVEL': 'DEBUG', 'JAVA_HOME': '/usr/lib/jvm/java-8-openjdk-amd64', 'CONDA_DIR': '/opt/conda', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_PORT': '8888', 'CONDA_VERSION': '4.8.2', 'SPARK_VER': '2.4.5', 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp', 'KUBERNETES_PORT_443_TCP_ADDR': '10.96.0.1', 'EG_CULL_IDLE_TIMEOUT': '3600', 'ENTERPRISE_GATEWAY_SERVICE_HOST': '10.107.231.185', 'KUBERNETES_PORT': 'tcp://10.96.0.1:443', 'PWD': '/usr/local/bin', 'HOME': '/home/jovyan', 'MINICONDA_MD5': '87e77f097f6ebb5127c77662dfc3165e', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_PROTO': 'tcp', 'EG_MIRROR_WORKING_DIRS': 'False', 'KUBERNETES_SERVICE_PORT_HTTPS': '443', 'DEBIAN_FRONTEND': 'noninteractive', 'KUBERNETES_PORT_443_TCP_PORT': '443', 'EG_KERNEL_LAUNCH_TIMEOUT': '60', 'EG_SSH_PORT': '2122', 'ENTERPRISE_GATEWAY_SERVICE_PORT_HTTP': '8888', 'EG_CULL_INTERVAL': '60', 'SPARK_HOME': '/opt/spark', 'NB_USER': 'jovyan', 'EG_KERNEL_WHITELIST': "['r_kubernetes','python_kubernetes','python_tf_kubernetes','python_tf_gpu_kubernetes','scala_kubernetes','spark_r_kubernetes','spark_python_kubernetes','spark_scala_kubernetes']", 'KUBERNETES_PORT_443_TCP': 'tcp://10.96.0.1:443', 'EG_CULL_CONNECTED': 'False', 'EG_PORT_RETRIES': '0', 'KG_PORT': '8888', 'ENTERPRISE_GATEWAY_SERVICE_PORT': '8888', 'SHELL': '/bin/bash', 'ENTERPRISE_GATEWAY_PORT': 'tcp://10.107.231.185:8888', 'ENTERPRISE_GATEWAY_PORT_8888_TCP': 'tcp://10.107.231.185:8888', 'EG_PORT': '8888', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_ADDR': '10.107.231.185', 'SHLVL': '0', 'LANGUAGE': 'en_US.UTF-8', 'EG_KERNEL_CLUSTER_ROLE': 'kernel-controller', 'KUBERNETES_SERVICE_PORT': '443', 'EG_NAMESPACE': 'enterprise-gateway', 'NB_GID': '100', 'KG_IP': '0.0.0.0', 'PATH': '/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'EG_IP': '0.0.0.0', 'KUBERNETES_SERVICE_HOST': '10.96.0.1', 'MINICONDA_VERSION': '4.8.2', 'KERNEL_GATEWAY': '1', 'KERNEL_USERNAME': 'jovyan', 'KERNEL_POD_NAME': 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e', 'KERNEL_SERVICE_ACCOUNT_NAME': 'default', 'KERNEL_NAMESPACE': 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e', 'KERNEL_IMAGE': 'elyra/kernel-py:dev', 'KERNEL_EXECUTOR_IMAGE': 'elyra/kernel-py:dev', 'KERNEL_UID': '1000', 'KERNEL_GID': '100', 'EG_MIN_PORT_RANGE_SIZE': '1000', 'EG_MAX_PORT_RANGE_RETRIES': '5', 'KERNEL_ID': '1c5d6e32-8c59-44e2-8a60-11499cbeb39e', 'KERNEL_LANGUAGE': 'python', 'EG_IMPERSONATION_ENABLED': 'False'}
[I 2020-06-12 04:46:52.689 EnterpriseGatewayApp] KubernetesProcessProxy: kernel launched. Kernel image: elyra/kernel-py:dev, KernelID: 1c5d6e32-8c59-44e2-8a60-11499cbeb39e, cmd: '['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', '1c5d6e32-8c59-44e2-8a60-11499cbeb39e', '--RemoteProcessProxy.response-address', '10.1.0.101:35523']'
[D 2020-06-12 04:46:53.198 EnterpriseGatewayApp] 1: Waiting to connect to k8s pod in namespace 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e'. Name: 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e', Status: 'Pending', Pod IP: 'None', KernelID: '1c5d6e32-8c59-44e2-8a60-11499cbeb39e'
[D 2020-06-12 04:46:53.707 EnterpriseGatewayApp] 2: Waiting to connect to k8s pod in namespace 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e'. Name: 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e', Status: 'Pending', Pod IP: 'None', KernelID: '1c5d6e32-8c59-44e2-8a60-11499cbeb39e'
[D 2020-06-12 04:46:54.215 EnterpriseGatewayApp] 3: Waiting to connect to k8s pod in namespace 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e'. Name: 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e', Status: 'Pending', Pod IP: 'None', KernelID: '1c5d6e32-8c59-44e2-8a60-11499cbeb39e'
[D 2020-06-12 04:46:54.725 EnterpriseGatewayApp] 4: Waiting to connect to k8s pod in namespace 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e'. Name: 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e', Status: 'Pending', Pod IP: 'None', KernelID: '1c5d6e32-8c59-44e2-8a60-11499cbeb39e'
[D 2020-06-12 04:46:55.234 EnterpriseGatewayApp] 5: Waiting to connect to k8s pod in namespace 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e'. Name: 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e', Status: 'Running', Pod IP: '10.1.0.102', KernelID: '1c5d6e32-8c59-44e2-8a60-11499cbeb39e'
[D 2020-06-12 04:46:55.234 EnterpriseGatewayApp] Received Payload 'e6F2P20OBPRUDCCCMS+bwcPpY8O3W7ZW8ysJySwK5zGoMH0/L33E7mIwFtXd9ZOpea7inYYDnLqE3Z+F/o2381n3VUlQIMGABSApsEG/+CNNQalnG7rfuIGyUZNVN46XZfk2ekh1hbJs5x9yYLSDNOJoZ/bhGX+EGkzyiK5HaFMkqEMAibEc1Fgm4lrHt4M5DTvQYfiJAPoaWYxZuPrPj8IWqWxvf2mZxnEX5T/E14P8uzDFig8ThqRLdU0Nyod4LWqPYf4GVweIn8/8uTBcyNhmIOixCBn6HvfMU3vFTFe/aMH5+Ayq8FAElSBvbzgbHeZwzmw7YQPu8DPIxHn3h9JV7Vh80ncSCZq9e5kpoZIDNPr2pg4QqGS8dkE2QtJa'
[D 2020-06-12 04:46:55.236 EnterpriseGatewayApp] Decrypted Payload '{"shell_port": 48099, "iopub_port": 34933, "stdin_port": 49035, "control_port": 57565, "hb_port": 45561, "ip": "0.0.0.0", "key": "24c69a4e-2175-4f1d-9783-5315b409c7ef", "transport": "tcp", "signature_scheme": "hmac-sha256", "kernel_name": "", "pid": "9", "pgid": "6", "comm_port": 49829}'
[D 2020-06-12 04:46:55.236 EnterpriseGatewayApp] Connect Info received from the launcher is as follows '{'shell_port': 48099, 'iopub_port': 34933, 'stdin_port': 49035, 'control_port': 57565, 'hb_port': 45561, 'ip': '0.0.0.0', 'key': '24c69a4e-2175-4f1d-9783-5315b409c7ef', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'pid': '9', 'pgid': '6', 'comm_port': 49829}'
[D 2020-06-12 04:46:55.236 EnterpriseGatewayApp] Host assigned to the Kernel is: 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e' '10.1.0.102'
[D 2020-06-12 04:46:55.236 EnterpriseGatewayApp] Established gateway communication to: 10.1.0.102:49829 for KernelID '1c5d6e32-8c59-44e2-8a60-11499cbeb39e'
[D 2020-06-12 04:46:55.238 EnterpriseGatewayApp] Received connection info for KernelID '1c5d6e32-8c59-44e2-8a60-11499cbeb39e' from host 'jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e': {'shell_port': 48099, 'iopub_port': 34933, 'stdin_port': 49035, 'control_port': 57565, 'hb_port': 45561, 'ip': '10.1.0.102', 'key': '24c69a4e-2175-4f1d-9783-5315b409c7ef', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'comm_port': 49829}...
[D 2020-06-12 04:46:55.238 EnterpriseGatewayApp] Connecting to: tcp://10.1.0.102:57565
[D 2020-06-12 04:46:55.239 EnterpriseGatewayApp] Connecting to: tcp://10.1.0.102:34933
[I 2020-06-12 04:46:55.240 EnterpriseGatewayApp] Kernel started: 1c5d6e32-8c59-44e2-8a60-11499cbeb39e, name: python_kubernetes
[D 2020-06-12 04:46:55.240 EnterpriseGatewayApp] Kernel args: {'kernel_name': 'python_kubernetes'}
[I 2020-06-12 04:46:55.240 EnterpriseGatewayApp] Culling kernels with idle durations > 3600 seconds at 60 second intervals ...
[I 200612 04:46:55 web:2250] 201 POST /api/kernels (10.1.0.99) 3004.44ms
[D 2020-06-12 04:47:55.246 EnterpriseGatewayApp] Polling every 60 seconds for kernels idle > 3600 seconds...
[D 2020-06-12 04:47:55.246 EnterpriseGatewayApp] kernel_id=1c5d6e32-8c59-44e2-8a60-11499cbeb39e, kernel_name=python_kubernetes, last_activity=2020-06-12 04:46:55.239712+00:00
```

#### Shutdown kernel
```
# curl -X DELETE http://enterprise-gateway.enterprise-gateway:8888/api/kernels/1c5d6e32-8c59-44e2-8a60-11499cbeb39e

[D 2020-06-12 04:50:15.364 EnterpriseGatewayApp] Clearing buffer for 1c5d6e32-8c59-44e2-8a60-11499cbeb39e
[I 2020-06-12 04:50:15.365 EnterpriseGatewayApp] Kernel shutdown: 1c5d6e32-8c59-44e2-8a60-11499cbeb39e
[D 2020-06-12 04:50:15.366 EnterpriseGatewayApp] Shutdown request sent to listener via gateway communication port.
[D 2020-06-12 04:50:16.716 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e.jovyan-1c5d6e32-8c59-44e2-8a60-11499cbeb39e, kernel ID: 1c5d6e32-8c59-44e2-8a60-11499cbeb39e has been terminated.
[I 200612 04:50:16 web:2250] 204 DELETE /api/kernels/1c5d6e32-8c59-44e2-8a60-11499cbeb39e (10.1.0.99) 1356.05ms
```

Now, "timed out" log is not printed, and there is no delay.

Thank you again for everything you’ve done!

**Comment by kevin-bates** [comment] 2020-06-12 13:33
This is excellent news @taeyeopkim1 - thank you for your detailed update!  We'll close this issue was #824 is merged.

**Closed** 2020-06-20 14:16 UTC
Labels: Kubernetes, Runtime
